# Generated by Django 5.2.7 on 2025-11-17 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('fabricante', models.CharField(max_length=120, verbose_name='Fabricante')),
                ('pmp_w', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pmp (W)')),
                ('vmp_v', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vmp (V)')),
                ('imp_a', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imp (A)')),
                ('voc_v', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Voc (V)')),
                ('isc_a', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Isc (A)')),
                ('eficiencia_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eficiência (%)')),
                ('power_tolerance', models.CharField(blank=True, default='', max_length=32, verbose_name='Power Tolerance')),
                ('num_celulas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de células')),
                ('temp_coeff_voc_pct_c', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Temperature Coefficient (Voc) (%/°C)')),
                ('temp_coeff_isc_pct_c', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Temperature Coefficient (Isc) (%/°C)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fabricante', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'fabricante'), name='uniq_nome_fabricante')],
            },
        ),
    ]
