# Generated by Django 5.2.7 on 2025-11-17 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backfill_rs_rp_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodule',
            name='diode_a',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.5)], verbose_name='Fator de idealidade (a)'),
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='rp_ohm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resistência paralelo Rp (Ω)'),
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='rs_ohm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resistência série Rs (Ω)'),
        ),
    ]
