# Generated by Django 5.2.7 on 2025-11-17 01:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enforce_not_null_rs_rp_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PVPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da planta')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('timezone', models.CharField(blank=True, default='', max_length=64, verbose_name='Fuso horário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvplants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planta FV',
                'verbose_name_plural': 'Plantas FV',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlantMonitoringCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(blank=True, default='', max_length=60, verbose_name='Provedor')),
                ('username', models.CharField(blank=True, default='', max_length=120, verbose_name='Login/usuário')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='Senha (plain por enquanto)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_cred', to='core.pvplant')),
            ],
            options={
                'verbose_name': 'Credencial de monitoramento',
                'verbose_name_plural': 'Credenciais de monitoramento',
            },
        ),
    ]
