# Generated by Django 5.2.7 on 2025-11-17 03:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_pvplant_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantmonitoringcredential',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.pvplant'),
        ),
        migrations.AlterField(
            model_name='pvplant',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, verbose_name='Fuso horário'),
        ),
        migrations.CreateModel(
            name='PlantCableSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('PV_CHAIN', 'Módulo–Módulo (string)'), ('STRING_HOME', 'String–Caixa/Combiner'), ('DC_MAIN', 'DC principal – Combiner/Inv'), ('AC_GRID', 'AC – Inversor–QDG/Rede'), ('GND', 'Aterramento'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Trecho')),
                ('description', models.CharField(blank=True, default='', max_length=120, verbose_name='Descrição')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Comprimento (m)')),
                ('cross_section_mm2', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seção (mm²)')),
                ('material', models.CharField(choices=[('CU', 'Cobre'), ('AL', 'Alumínio')], default='CU', max_length=2, verbose_name='Material')),
                ('qty_parallel', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Condutores em paralelo')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_segments', to='core.pvplant')),
            ],
            options={
                'verbose_name': 'Trecho de cabeamento',
                'verbose_name_plural': 'Cabeamento da planta',
                'ordering': ['plant', 'segment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PVInverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=120, verbose_name='Fabricante')),
                ('modelo', models.CharField(max_length=120, verbose_name='Modelo')),
                ('p_ac_nom_w', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potência AC nominal (W)')),
                ('v_ac_nom_v', models.PositiveIntegerField(default=230, verbose_name='Tensão AC nominal (V)')),
                ('vdc_mppt_min_v', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='MPPT min (V)')),
                ('vdc_mppt_max_v', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='MPPT max (V)')),
                ('vdc_abs_max_v', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='VDC máx. absoluto (V)')),
                ('mppt_count', models.PositiveSmallIntegerField(default=1, verbose_name='Qtd MPPT')),
                ('strings_por_mppt_max', models.PositiveSmallIntegerField(default=1, verbose_name='Strings/MPPT (máx.)')),
                ('eficiencia_max_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eficiência máx. (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fabricante', 'modelo'],
                'constraints': [models.UniqueConstraint(fields=('fabricante', 'modelo'), name='uniq_inverter_fabricante_modelo')],
            },
        ),
        migrations.CreateModel(
            name='PVPlantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strings_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Strings (qtd)')),
                ('modules_per_string', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Módulos por string')),
                ('modules_total', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Módulos totais')),
                ('tilt_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Inclinação (graus)')),
                ('azimuth_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Azimute (graus)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_details', to='core.pvinverter')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_details', to='core.pvmodule')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.pvplant')),
            ],
            options={
                'verbose_name': 'Detalhes da planta',
                'verbose_name_plural': 'Detalhes da planta',
            },
        ),
    ]
