# Generated by Django 5.2.7 on 2025-11-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plantmonitoringcredential_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvplant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pvplantdetails',
            options={},
        ),
    ]
