# Generated by Django 5.2.7 on 2025-11-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_pvplantdetails_and_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmonitoringcredential',
            name='provedor',
            field=models.CharField(choices=[('GROWATT', 'Growatt')], default='GROWATT', max_length=60, verbose_name='Provedor'),
        ),
    ]
