# Generated by Django 5.2.7 on 2025-11-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_plantmonitoringcredential_provedor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plantmonitoringcredential',
            constraint=models.UniqueConstraint(fields=('plant', 'provedor'), name='uniq_plant_provedor'),
        ),
    ]
