# Generated by Django 5.2.7 on 2026-01-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plantmonitoringcredential_uniq_plant_provedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmonitoringcredential',
            name='provedor',
            field=models.CharField(choices=[('GROWATT', 'Growatt'), ('RENOVIGI', 'Renovigi')], default='GROWATT', max_length=60, verbose_name='Provedor'),
        ),
    ]
