# Generated by Django 5.2.7 on 2026-01-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_plantmonitoringcredential_provedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShineCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('token', models.TextField()),
                ('secret', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShineDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pn', models.CharField(max_length=40)),
                ('devcode', models.CharField(max_length=40)),
                ('devaddr', models.CharField(max_length=16)),
                ('sn', models.CharField(max_length=64)),
                ('i18n', models.CharField(default='pt_BR', max_length=16)),
                ('lang', models.CharField(default='pt', max_length=8)),
                ('odd_even_row', models.CharField(blank=True, default='', max_length=16)),
                ('timezone_name', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('timestamp_index', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shinecredential')),
            ],
        ),
        migrations.CreateModel(
            name='ShineProtocolSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.shinedevice')),
            ],
        ),
        migrations.CreateModel(
            name='ShineReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_utc', models.DateTimeField()),
                ('fields', models.JSONField(default=dict)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shinedevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'ts_utc'], name='core_shiner_device__5548de_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'ts_utc'), name='uniq_shine_device_ts')],
            },
        ),
    ]
