# Generated by Django 5.2.7 on 2026-01-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shinecredential_shinedevice_shineprotocolschema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='company_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Company key (Renovigi)'),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
