# Generated by Django 5.2.7 on 2026-01-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_plantmonitoringcredential_company_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantmonitoringcredential',
            name='company_key',
        ),
        migrations.RemoveField(
            model_name='plantmonitoringcredential',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='plantmonitoringcredential',
            name='token',
        ),
        migrations.RemoveField(
            model_name='plantmonitoringcredential',
            name='token_expires_at',
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_devaddr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_devcode',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_devices_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_i18n',
            field=models.CharField(blank=True, default='pt_BR', max_length=20),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_lang',
            field=models.CharField(blank=True, default='pt_BR', max_length=20),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_plantid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_plants_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_pn',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='plantmonitoringcredential',
            name='shinemonitor_sn',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
