# Generated by Django 5.2.7 on 2026-01-21 21:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_plantmonitoringcredential_company_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('series_key', models.CharField(max_length=255)),
                ('last_ok_day', models.DateField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='never', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_states', to='core.pvplant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'source', 'series_key'), name='uniq_ingest_state')],
            },
        ),
        migrations.CreateModel(
            name='InverterSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(max_length=255)),
                ('ts', models.DateTimeField(db_index=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverter_samples', to='core.pvplant')),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'device_key', 'ts'], name='core_invert_plant_i_0db947_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'device_key', 'ts'), name='uniq_inverter_sample')],
            },
        ),
    ]
