# Generated by Django 5.2.7 on 2026-01-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dataingeststate_invertersample'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterOperationalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(default='RENOVIGI', max_length=60)),
                ('pn', models.CharField(max_length=80)),
                ('devcode', models.CharField(max_length=80)),
                ('devaddr', models.IntegerField()),
                ('sn', models.CharField(max_length=120)),
                ('ts_utc', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opdata', to='core.pvplant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'provedor', 'pn', 'devcode', 'devaddr', 'sn', 'ts_utc'), name='uniq_opdata_device_ts')],
            },
        ),
    ]
