# Generated by Django 5.2.7 on 2026-01-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_inverteroperationaldata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inverteroperationaldata',
            options={'ordering': ['ts_utc']},
        ),
        migrations.AddField(
            model_name='inverteroperationaldata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inverteroperationaldata',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='inverteroperationaldata',
            index=models.Index(fields=['plant', 'ts_utc'], name='idx_opdata_plant_ts'),
        ),
        migrations.AddIndex(
            model_name='inverteroperationaldata',
            index=models.Index(fields=['plant', 'provedor', 'pn', 'devcode', 'devaddr', 'sn', 'ts_utc'], name='idx_opdata_device_ts'),
        ),
        migrations.AddIndex(
            model_name='inverteroperationaldata',
            index=models.Index(fields=['plant', 'provedor'], name='idx_opdata_plant_provider'),
        ),
    ]
