# Generated by Django 5.2.7 on 2026-01-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_inverteroperationaldata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('NSRDB', 'NSRDB (NREL)')], default='NSRDB', max_length=20)),
                ('ts_utc', models.DateTimeField(db_index=True)),
                ('interval_min', models.PositiveSmallIntegerField(default=60)),
                ('ghi', models.FloatField(blank=True, null=True)),
                ('dni', models.FloatField(blank=True, null=True)),
                ('dhi', models.FloatField(blank=True, null=True)),
                ('temp_air', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('rh', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteo_records', to='core.pvplant')),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'source', 'ts_utc'], name='core_meteor_plant_i_50fa91_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'source', 'ts_utc'), name='uniq_meteo_plant_source_tsutc')],
            },
        ),
    ]
