# Generated by Django 5.2.7 on 2026-01-22 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_meteorecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorecord',
            name='gti',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorecord',
            name='interval_min',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meteorecord',
            name='source',
            field=models.CharField(choices=[('OPENMETEO', 'Open-Meteo'), ('NSRDB', 'NSRDB (NREL)')], default='OPENMETEO', max_length=20),
        ),
    ]
