# Generated by Django 5.2.7 on 2026-01-23 01:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_meteorecord_gti_alter_meteorecord_interval_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvplantdetails',
            name='azimuth_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)], verbose_name='Azimute (graus)'),
        ),
        migrations.CreateModel(
            name='PVPlantMergedRecord15m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_oper', models.CharField(choices=[('SHINEMONITOR', 'ShineMonitor/Renovigi'), ('GROWATT', 'Growatt'), ('MANUAL', 'Manual/Outros')], default='SHINEMONITOR', max_length=30)),
                ('source_meteo', models.CharField(choices=[('OPENMETEO', 'Open-Meteo'), ('NSRDB', 'NSRDB (NREL)')], default='OPENMETEO', max_length=20)),
                ('ts_utc', models.DateTimeField(db_index=True)),
                ('interval_min', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('p_dc_w', models.FloatField(blank=True, null=True)),
                ('p_ac_w', models.FloatField(blank=True, null=True)),
                ('v_dc_v', models.FloatField(blank=True, null=True)),
                ('i_dc_a', models.FloatField(blank=True, null=True)),
                ('v_ac_v', models.FloatField(blank=True, null=True)),
                ('i_ac_a', models.FloatField(blank=True, null=True)),
                ('e_ac_wh_15', models.FloatField(blank=True, null=True)),
                ('inv_n', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inv_coverage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('flag_low_coverage', models.BooleanField(default=False)),
                ('ghi', models.FloatField(blank=True, null=True)),
                ('dni', models.FloatField(blank=True, null=True)),
                ('dhi', models.FloatField(blank=True, null=True)),
                ('gti', models.FloatField(blank=True, null=True)),
                ('temp_air', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('rh', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('flag_meteo_missing', models.BooleanField(default=False)),
                ('flag_inv_missing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_15m', to='core.pvplant')),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'ts_utc'], name='core_pvplan_plant_i_49fc3e_idx'), models.Index(fields=['plant', 'source_oper', 'source_meteo', 'ts_utc'], name='core_pvplan_plant_i_4b9b5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'source_oper', 'source_meteo', 'interval_min', 'ts_utc'), name='uniq_merged15m_plant_sources_interval_tsutc')],
            },
        ),
    ]
