# Generated by Django 5.2.7 on 2026-01-23 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_pvplantdetails_azimuth_deg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvplantdetails',
            name='azimuth_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Azimute (graus)'),
        ),
    ]
