# Generated by Django 5.2.7 on 2026-01-23 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_pvplantdetails_azimuth_deg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvplantdetails',
            name='k_sys',
            field=models.DecimalField(decimal_places=3, default=0.9, max_digits=6, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.2)], verbose_name='k_sys (DC→AC)'),
        ),
        migrations.AddField(
            model_name='pvplantdetails',
            name='noct_c',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(70)], verbose_name='TNOCT (°C)'),
        ),
    ]
