# Generated by Django 5.2.7 on 2026-01-26 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pvplantdetails_k_sys_pvplantdetails_noct_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVPlantStringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=60, verbose_name='Nome')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('mppt', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='MPPT (opcional)')),
                ('strings_qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qtd de strings')),
                ('modules_per_string', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Módulos por string')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_configs', to='core.pvplantdetails')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['details'], name='core_pvplan_details_9a6be5_idx')],
            },
        ),
    ]
