# Generated by Django 5.2.7 on 2026-01-27 15:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pvplantstringconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvplantdetails',
            name='k_sys',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.900'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('1.2'))], verbose_name='k_sys (DC→AC)'),
        ),
    ]
