# Generated by Django 5.2.7 on 2026-01-31 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_pvplantdetails_k_sys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvplantdetails',
            name='azimuth_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)], verbose_name='Azimute (graus)'),
        ),
    ]
