# Generated by Django 5.2.7 on 2026-02-01 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_pvplantdetails_azimuth_deg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDiagnostic15m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_utc', models.DateTimeField(db_index=True, verbose_name='Timestamp (UTC)')),
                ('rca_code', models.SmallIntegerField(default=0, verbose_name='RCA code')),
                ('rca_label', models.CharField(blank=True, default='invalid', max_length=40, verbose_name='RCA label')),
                ('valid', models.BooleanField(default=False)),
                ('g_poa', models.FloatField(blank=True, null=True)),
                ('tcell_c', models.FloatField(blank=True, null=True)),
                ('pac_real_w', models.FloatField(blank=True, null=True)),
                ('pac_model_w', models.FloatField(blank=True, null=True)),
                ('mismatch_rel', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics_15m', to='core.pvplant')),
            ],
            options={
                'verbose_name': 'Diagnóstico 15 min',
                'verbose_name_plural': 'Diagnósticos 15 min',
                'indexes': [models.Index(fields=['plant', 'ts_utc'], name='core_plantd_plant_i_118442_idx'), models.Index(fields=['plant', 'rca_code', 'ts_utc'], name='core_plantd_plant_i_828ed2_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'ts_utc'), name='uniq_plant_ts_utc_diag15m')],
            },
        ),
    ]
