# Generated by Django 5.2.7 on 2026-02-12 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_plantdiagnostic15m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvplantmergedrecord15m',
            name='gti',
            field=models.FloatField(blank=True, help_text='POA/GTI se disponível', null=True),
        ),
        migrations.AlterField(
            model_name='pvplantmergedrecord15m',
            name='interval_min',
            field=models.PositiveSmallIntegerField(default=15, help_text='Intervalo do bucket (min). Para esta tabela, deve ser 15.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pvplantmergedrecord15m',
            name='inv_coverage',
            field=models.FloatField(blank=True, help_text='Cobertura (0..1) de amostras do inversor no bucket.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='pvplantmergedrecord15m',
            name='pressure',
            field=models.FloatField(blank=True, help_text='Pressão (Pa)', null=True),
        ),
        migrations.AlterField(
            model_name='pvplantmergedrecord15m',
            name='rh',
            field=models.FloatField(blank=True, help_text='Umidade relativa (%)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='pvplantmergedrecord15m',
            name='source_meteo',
            field=models.CharField(choices=[('OPENMETEO', 'Open-Meteo'), ('NSRDB', 'NSRDB (NREL)')], db_index=True, default='OPENMETEO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pvplantmergedrecord15m',
            name='source_oper',
            field=models.CharField(choices=[('SHINEMONITOR', 'ShineMonitor/Renovigi'), ('GROWATT', 'Growatt'), ('MANUAL', 'Manual/Outros')], db_index=True, default='SHINEMONITOR', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='pvplantmergedrecord15m',
            constraint=models.CheckConstraint(condition=models.Q(('interval_min', 15)), name='chk_merged15m_interval_is_15'),
        ),
        migrations.AddConstraint(
            model_name='pvplantmergedrecord15m',
            constraint=models.CheckConstraint(condition=models.Q(('inv_coverage__isnull', True), models.Q(('inv_coverage__gte', 0.0), ('inv_coverage__lte', 1.0)), _connector='OR'), name='chk_merged15m_inv_coverage_0_1'),
        ),
        migrations.AddConstraint(
            model_name='pvplantmergedrecord15m',
            constraint=models.CheckConstraint(condition=models.Q(('e_ac_wh_15__isnull', True), ('e_ac_wh_15__gte', 0.0), _connector='OR'), name='chk_merged15m_e_ac_wh_15_nonneg'),
        ),
    ]
