# Generated by Django 5.2.7 on 2026-02-13 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_pvplantmergedrecord15m_gti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantdiagnostic15m',
            options={'ordering': ['plant_id', 'ts_utc'], 'verbose_name': 'Diagnóstico 15 min', 'verbose_name_plural': 'Diagnósticos 15 min'},
        ),
        migrations.RenameIndex(
            model_name='plantdiagnostic15m',
            new_name='idx_diag15m_plant_ts',
            old_name='core_plantd_plant_i_118442_idx',
        ),
        migrations.RenameIndex(
            model_name='plantdiagnostic15m',
            new_name='idx_diag15m_plant_code_ts',
            old_name='core_plantd_plant_i_828ed2_idx',
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='g_poa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='GPOA/POA (W/m²)'),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='mismatch_rel',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Mismatch relativo'),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='pac_model_w',
            field=models.FloatField(blank=True, null=True, verbose_name='Pac modelo (W)'),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='pac_real_w',
            field=models.FloatField(blank=True, null=True, verbose_name='Pac real (W)'),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='rca_code',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='RCA code'),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='tcell_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Tcell (°C)'),
        ),
    ]
