# Generated by Django 5.2.7 on 2026-02-23 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_plantdiagnostic15m_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='alarm_code',
            field=models.IntegerField(blank=True, help_text='Código do alarme/falha (se disponível).', null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='alarm_sev',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Severidade agregada no bucket (MVP: 0 OK, 2 fault).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt1_idc_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt1_vdc_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt2_idc_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt2_vdc_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt3_idc_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt3_vdc_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt4_idc_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='mppt4_vdc_v',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
