# Generated by Django 5.2.7 on 2026-02-25 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_pvplantmergedrecord15m_alarm_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPPTDiagnostic15m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_oper', models.CharField(db_index=True, max_length=30)),
                ('mppt', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('ts_utc', models.DateTimeField(db_index=True, verbose_name='Timestamp (UTC)')),
                ('model_version', models.CharField(blank=True, default='mppt_gnn_v1', max_length=64)),
                ('pred_code', models.SmallIntegerField(default=0)),
                ('pred_label', models.CharField(blank=True, default='normal', max_length=40)),
                ('pred_pmax', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('proba', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mppt_diagnostics_15m', to='core.pvplant')),
            ],
            options={
                'verbose_name': 'Diagnóstico MPPT 15 min',
                'verbose_name_plural': 'Diagnósticos MPPT 15 min',
                'ordering': ['plant_id', 'source_oper', 'mppt', 'ts_utc'],
                'indexes': [models.Index(fields=['plant', 'ts_utc'], name='idx_mpptdiag_plant_ts'), models.Index(fields=['plant', 'source_oper', 'ts_utc'], name='idx_mpptdiag_src_ts'), models.Index(fields=['plant', 'source_oper', 'mppt', 'ts_utc'], name='idx_mpptdiag_src_mppt_ts')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'source_oper', 'mppt', 'ts_utc'), name='uniq_mpptdiag_plant_src_mppt_ts')],
            },
        ),
    ]
