# Generated by Django 5.2.7 on 2026-03-11 03:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_mpptdiagnostic15m'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_oper', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('source_meteo', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('ts_start_utc', models.DateTimeField(db_index=True)),
                ('ts_end_utc', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('detector_version', models.CharField(blank=True, default='residual_v1', max_length=64)),
                ('detector_score_max', models.FloatField(blank=True, null=True)),
                ('detector_score_mean', models.FloatField(blank=True, null=True)),
                ('severity_score', models.FloatField(blank=True, null=True)),
                ('energy_loss_wh', models.FloatField(blank=True, null=True)),
                ('event_label_prelim', models.CharField(blank=True, default='unknown', max_length=64)),
                ('known_vs_unknown', models.CharField(db_index=True, default='pending', max_length=16)),
                ('final_label', models.CharField(blank=True, default='', max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('novelty_score', models.FloatField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fault Event',
                'verbose_name_plural': 'Fault Events',
                'ordering': ['plant_id', 'ts_start_utc'],
            },
        ),
        migrations.CreateModel(
            name='FaultEventMPPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_oper', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('mppt', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('model_version', models.CharField(blank=True, default='event_rules_v1', max_length=64)),
                ('pred_code', models.SmallIntegerField(default=99)),
                ('pred_label', models.CharField(blank=True, default='unknown_fault', max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('novelty_score', models.FloatField(blank=True, null=True)),
                ('contribution', models.JSONField(blank=True, null=True)),
                ('proba', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fault Event MPPT',
                'verbose_name_plural': 'Fault Event MPPT',
                'ordering': ['event_id', 'mppt'],
            },
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='anomaly_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='cusum_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='detector_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='detector_version',
            field=models.CharField(blank=True, default='residual_v1', max_length=64),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='ewma_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='stable_sky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='plantdiagnostic15m',
            index=models.Index(fields=['plant', 'anomaly_flag', 'ts_utc'], name='idx_diag15m_plant_anom_ts'),
        ),
        migrations.AddField(
            model_name='faultevent',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_events', to='core.pvplant'),
        ),
        migrations.AddField(
            model_name='faulteventmppt',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mppt_predictions', to='core.faultevent'),
        ),
        migrations.AddIndex(
            model_name='faultevent',
            index=models.Index(fields=['plant', 'ts_start_utc'], name='idx_faultevent_plant_start'),
        ),
        migrations.AddIndex(
            model_name='faultevent',
            index=models.Index(fields=['plant', 'status', 'ts_start_utc'], name='idx_faultevent_status_start'),
        ),
        migrations.AddIndex(
            model_name='faultevent',
            index=models.Index(fields=['plant', 'final_label', 'ts_start_utc'], name='idx_faultevent_label_start'),
        ),
        migrations.AddConstraint(
            model_name='faultevent',
            constraint=models.UniqueConstraint(fields=('plant', 'source_oper', 'ts_start_utc', 'ts_end_utc', 'detector_version'), name='uniq_faultevent_window_detector'),
        ),
        migrations.AddConstraint(
            model_name='faultevent',
            constraint=models.CheckConstraint(condition=models.Q(('ts_end_utc__gte', models.F('ts_start_utc'))), name='chk_faultevent_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='faulteventmppt',
            index=models.Index(fields=['event', 'mppt'], name='idx_faulteventmppt_event_mppt'),
        ),
        migrations.AddIndex(
            model_name='faulteventmppt',
            index=models.Index(fields=['event', 'pred_code'], name='idx_faulteventmppt_event_code'),
        ),
        migrations.AddConstraint(
            model_name='faulteventmppt',
            constraint=models.UniqueConstraint(fields=('event', 'mppt', 'model_version'), name='uniq_faulteventmppt_event_mppt_model'),
        ),
    ]
