# Generated by Django 5.2.7 on 2026-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_faultevent_faulteventmppt_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plantdiagnostic15m',
            name='uniq_plant_ts_utc_diag15m',
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='source_meteo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Fonte meteorológica usada para este diagnóstico 15 min.', max_length=20),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='source_oper',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Fonte operativa usada para este diagnóstico 15 min.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='plantdiagnostic15m',
            index=models.Index(fields=['plant', 'source_oper', 'source_meteo', 'ts_utc'], name='idx_diag15m_sources_ts'),
        ),
        migrations.AddIndex(
            model_name='plantdiagnostic15m',
            index=models.Index(fields=['plant', 'detector_version', 'ts_utc'], name='idx_diag15m_detector_ts'),
        ),
        migrations.AddConstraint(
            model_name='plantdiagnostic15m',
            constraint=models.UniqueConstraint(fields=('plant', 'source_oper', 'source_meteo', 'detector_version', 'ts_utc'), name='uniq_diag15m_plant_sources_detector_ts'),
        ),
    ]
