# Generated by Django 5.2.7 on 2026-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_plantdiagnostic15m_uniq_plant_ts_utc_diag15m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='flag_inv_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='flag_meteo_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='freq_hz',
            field=models.FloatField(blank=True, null=True, verbose_name='Frequência AC (Hz)'),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='i_ac_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Iac (A)'),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='i_dc_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Idc (A)'),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='inv_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='v_ac_v',
            field=models.FloatField(blank=True, null=True, verbose_name='Vac (V)'),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='v_dc_v',
            field=models.FloatField(blank=True, null=True, verbose_name='Vdc (V)'),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='freq_hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='pf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='qac_var',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
