# Generated by Django 5.2.7 on 2026-03-16 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_plantdiagnostic15m_flag_inv_missing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdiagnostic15m',
            old_name='flag_inv_missing',
            new_name='direct_grid_evidence',
        ),
        migrations.RenameField(
            model_name='plantdiagnostic15m',
            old_name='flag_meteo_missing',
            new_name='fine_diag_allowed',
        ),
        migrations.RemoveField(
            model_name='plantdiagnostic15m',
            name='i_dc_a',
        ),
        migrations.RemoveField(
            model_name='plantdiagnostic15m',
            name='inv_coverage',
        ),
        migrations.RemoveField(
            model_name='plantdiagnostic15m',
            name='v_dc_v',
        ),
        migrations.RemoveField(
            model_name='pvplantmergedrecord15m',
            name='pf',
        ),
        migrations.RemoveField(
            model_name='pvplantmergedrecord15m',
            name='qac_var',
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='alarm_code_oper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='alarm_sev_oper',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='diagnosis_confidence',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='diagnosis_label',
            field=models.CharField(blank=True, default='invalid', max_length=64),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='domain_label',
            field=models.CharField(blank=True, default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='evidence_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='irradiance_tier',
            field=models.CharField(blank=True, default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='meteo_quality_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='state_label',
            field=models.CharField(blank=True, default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='zero_injection_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='detector_version',
            field=models.CharField(blank=True, default='hybrid_rules_v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='freq_hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='i_ac_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='rca_label',
            field=models.CharField(blank=True, default='invalid', max_length=64, verbose_name='RCA label'),
        ),
        migrations.AlterField(
            model_name='plantdiagnostic15m',
            name='v_ac_v',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
