# Generated by Django 5.2.7 on 2026-03-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_flag_inv_missing_plantdiagnostic15m_direct_grid_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorecord',
            name='flag_meteo_artifact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='flag_meteo_interpolated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='flag_meteo_low_confidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='flag_meteo_outlier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meteorecord',
            name='meteo_qc_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='flag_meteo_artifact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='flag_meteo_interpolated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='flag_meteo_low_confidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='flag_meteo_outlier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pvplantmergedrecord15m',
            name='meteo_qc_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
