# Generated by Django 5.2.7 on 2026-03-29 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_meteorecord_flag_meteo_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultevent',
            name='confidence_notes_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faultevent',
            name='data_reliability_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='faultevent',
            name='data_reliability_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='faultevent',
            name='detection_confidence_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='faultevent',
            name='detection_confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='faultevent',
            name='diagnosis_confidence_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='faultevent',
            name='diagnosis_confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='confidence_notes_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='data_reliability_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='data_reliability_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='detection_confidence_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='detection_confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='diagnosis_confidence_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='plantdiagnostic15m',
            name='diagnosis_confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
