# Generated by Django 5.2.7 on 2026-04-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_faultevent_confidence_notes_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundTruthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_oper', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('source_meteo', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('detector_version', models.CharField(blank=True, default='mismatch_runtime_v1', max_length=64)),
                ('ts_start_utc', models.DateTimeField(db_index=True)),
                ('ts_end_utc', models.DateTimeField(db_index=True)),
                ('truth_state', models.CharField(choices=[('confirmed', 'Confirmed fault'), ('normal', 'Normal window'), ('uncertain', 'Uncertain'), ('dismissed', 'Dismissed')], db_index=True, default='confirmed', max_length=16)),
                ('truth_label', models.CharField(blank=True, db_index=True, default='unknown', max_length=64)),
                ('truth_group', models.CharField(blank=True, db_index=True, default='unknown', max_length=32)),
                ('annotation_source', models.CharField(blank=True, default='specialist_review', max_length=32)),
                ('annotation_confidence', models.CharField(blank=True, default='B', max_length=8)),
                ('created_by', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_fault_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_ground_truth_events', to='core.faultevent')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_truth_events', to='core.pvplant')),
            ],
            options={
                'verbose_name': 'Ground Truth Event',
                'verbose_name_plural': 'Ground Truth Events',
                'ordering': ['plant_id', 'ts_start_utc'],
                'indexes': [models.Index(fields=['plant', 'ts_start_utc'], name='idx_gt_event_plant_start'), models.Index(fields=['plant', 'truth_state', 'ts_start_utc'], name='idx_gt_event_state_start'), models.Index(fields=['plant', 'truth_label', 'ts_start_utc'], name='idx_gt_event_label_start')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ts_end_utc__gte', models.F('ts_start_utc'))), name='chk_groundtruth_end_after_start')],
            },
        ),
    ]
