"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from .runtime_paths import runtime_base_dir
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
BASE_DIR: Path = runtime_base_dir()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "change-me-in-prod")
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@8goz41^$w#icx*3wr6%q-)uzjc0jcg7fk75(15ji_k89g*nz*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # antes de django.contrib.staticfiles
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Static
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"   # destino do collectstatic
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Banco (SQLite) em pasta de dados do usuário (gravável fora do _MEIPASS)
def _user_data_dir() -> Path:
    home = Path.home()
    if os.name == "nt":
        base = Path(os.getenv("APPDATA", home / "AppData" / "Roaming"))
    elif sys.platform == "darwin":
        base = home / "Library" / "Application Support"
    else:
        base = Path(os.getenv("XDG_DATA_HOME", home / ".local" / "share"))
    d = base / "SolarControl"
    d.mkdir(parents=True, exist_ok=True)
    return d

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _user_data_dir() / "solar.sqlite3",
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"          # para onde vai após login
LOGOUT_REDIRECT_URL = "login"        # para onde vai após logout

# Em desenvolvimento, envia o e-mail de reset para o console:
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@exemplo.com"


#---------------------------------
#-------------------NREL
#---------------------------------
NREL_API_KEY = os.environ.get("IiPW4sbjyMmn0U3p0fKinYhv9CWBr3aA8hDLir5i")
NREL_FULL_NAME = os.environ.get("NREL_FULL_NAME", "Allan+Braz")  # usar '+' no lugar de espaço
NREL_EMAIL = os.environ.get("NREL_EMAIL", "allan.dasilva@utec.edu.uy")
NREL_AFFILIATION = os.environ.get("NREL_AFFILIATION", "UTEC")
NREL_REASON = os.environ.get("NREL_REASON", "research")
NREL_MAILING_LIST = os.environ.get("NREL_MAILING_LIST", "false")  # 'true'/'false'


#---------------------------------
#-------------------RENOVIGI
#---------------------------------
RENOVIGI_BASE_URL = "https://web.shinemonitor.com/public/"
RENOVIGI_COMPANY_KEY = "bnrl_frRFjEz8Mkn"
RENOVIGI_HTTP_TIMEOUT = 30.0

# Aliases para compatibilidade com código legado (se existir)
SHINEMONITOR_BASE_URL = RENOVIGI_BASE_URL
SHINEMONITOR_HTTP_TIMEOUT = RENOVIGI_HTTP_TIMEOUT
# Controle de download
RENOVIGI_PAGE_SIZE = 200      # ajuste conforme API/DevTools
RENOVIGI_SLEEP_SEC = 0.3      # reduz chance de ERR_OVER_LIMITED
RENOVIGI_MAX_RETRIES = 5